#!/bin/sh

killall -q sxhkd; sxhkd &
setxkbmap br &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config pointer_motion_interval 5
bspc config focus_follows_pointer   true
bspc config ignore_ewmh_focus       true
bspc config pointer_follows_monitor true

bspc config border_width  2
bspc config window_gap    8

bspc config split_ratio          0.52
#bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#61afef"
bspc config normal_border_color  "#1e222a"

# Ordering windows
bspc rule -a kitty           desktop='^1' follow=on
bspc rule -a Google-chrome   desktop='^2'
bspc rule -a Brave-browser   desktop='^2'
bspc rule -a vlc             desktop='^2'
bspc rule -a discord         desktop='^3'
bspc rule -a Spotify         desktop='^4'
bspc rule -a Steam           desktop='^6'
bspc rule -a "Steam:*:Friends List" desktop='^6' state=floating
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a Lutris          desktop='^7'
bspc rule -a Gimp-2.10       desktop='^7'
bspc rule -a Code            desktop='^7'
bspc rule -a qBittorrent     desktop='^8'
bspc rule -a Evince          desktop='^8'

bspc rule -a feh                state=floating
bspc rule -a Org.gnome.Nautilus state=floating

monitor_width=1920
monitor_heigh=1080
pip_width=$(($monitor_width / 4))
pip_heigh=$(($monitor_heigh / 4))
bspc rule -a "*:*:Picture-in-picture" \
  state=floating \
  rectangle=${pip_width}x${pip_heigh}+$(($monitor_width - $pip_width - 12))+$(($monitor_heigh - $pip_heigh - 12))

# games
bspc rule -a robloxplayerlauncher.exe desktop='^2' state=floating
bspc rule -a robloxplayerbeta.exe     desktop='^5'
bspc rule -a hl2_linux                desktop='^5'

steamlib=$HOME/.steam/steam/
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')

for game in $mygames; do
  bspc rule -a steam_app_$game desktop='^5'
done


# Polybar
$HOME/.config/polybar/launch.sh &

killall -q dunst; dunst &
