#!/bin/bash

source ~/scripts/colors.conf


_pacman=$(pacman -Qu --color always)
_pacman_number=$(sed "/^$/d" <<< "$_pacman" | wc -l)

_aur=$(paru -Qua --color always)
_aur_number=$(sed "/^$/d" <<< "$_aur" | wc -l)

_flatpak=$(flatpak remote-ls --updates --columns=name,branch)
_flatpak_number=$(sed "/^$/d" <<< "$_flatpak" | wc -l)

_total=$(( $_pacman_number + $_aur_number + $_flatpak_number ))


get() {
  if [[ $_total -ne 0 ]]; then
    if [[ $verbose -ne 1 ]]; then
      echo $_total
    else
      echo -e "\n${bold_red}[󱇬 ]${bold_gray} Total packages ${bold_red}($total)${end}"
      if [[ $_pacman_number -ne 0 ]]; then
        echo -e "  ${bold_yellow}[󰮯 ]${bold_gray} Pacman packages ${bold_yellow}($_pacman_number)${end}"
        awk '{ print "    " $0 }' <<< "$_pacman"
      fi
      if [[ $_aur_number -ne 0 ]]; then
        echo -e "\n  ${bold_green}[󰣇 ]${bold_gray} AUR packages ${bold_green}($_aur_number)${end}"
        awk '{ print "    " $0 }' <<< "$_aur"
      fi
      if [[ $_flatpak_number -ne 0 ]]; then
        echo -e "\n  ${bold_blue}[󰏗 ]${bold_gray} Flatpak packages ${bold_blue}($_flatpak_number)${end}"
        awk '{ print "    " $0 }' <<< "$_flatpak"
      fi
    fi
  else
    echo 0
  fi
}

write() {
  cat << EOF > ~/.cache/.updates_available
total:   ${_total}
pacman:  ${_pacman_number}
aur:     ${_aur_number}
flatpak: ${_flatpak_number}
EOF
}

update_archlinux_keyring() {
  if "${_pacman[@]}" =~ "archlinux-keyring"; then
    sudo pacman -Sy archlinux-keyring
  fi
}

update() {
  verbose=1
  get
  printf "\n${bold_magenta}[ ? ]${bold_gray} " && read -p "Update all ? " input
  for w in "$input" ; do
    case "$w" in
      [yY]|[yY][eE][sS])
        update_archlinux_keyring
        echo -e "${bold_yellow}[󰮯 ]${bold_gray} Updating pacman packages${end}"
        sudo pacman -Syyu

        echo -e "\n${bold_green}[󰣇 ]${bold_gray} Updating AUR packages${end}"
        paru -Syua

        echo -e "\n${bold_blue}[󰏗 ]${bold_gray} Updating flatpak packages${end}"
        flatpak -y update

        break
        ;;
      pacman)
        update_archlinux_keyring
        echo -e "${bold_yellow}[󰮯 ]${bold_gray} Updating pacman packages${end}"
        sudo pacman -Syyu --noconfirm
        ;;
      aur|AUR)
        update_archlinux_keyring
        echo -e "\n${bold_green}[󰣇 ]${bold_gray} Updating AUR packages${end}"
        paru -Syua --noconfirm
        ;;
      flatpak)
        echo -e "\n${bold_blue}[󰏗 ]${bold_gray} Updating flatpak packages${end}"
        flatpak -y update
        ;;
      *)
        ;;
    esac
  done
  echo -e "\n${bold_green}[󰸞 ]${bold_gray} Done - Press enter to exit${end}" && read
}

_shutdown() {
  if [[ $(awk '/_total/ { print $2 }' ~/.cache/.updates_available) -gt 100 ]] ; then
    if [[ "$(nmcli networking connectivity)" != "none" ]] ; then
      kitty sh -c "~/scripts/updates update"
      sh -c "~/scripts/updates write"
      [[ $(awk '/_total/ { print $2 }' ~/.cache/.updates_available) -eq 0 ]] && shutdown now
    fi
  else
    shutdown now
  fi
}


while [[ "$1" ]]; do
  case "$1" in
    -v|--verbose)
      verbose=1
      ;;
    get)
      get       ; exit
      ;;
    write)
      write     ; exit
      ;;
    update)
      update    ; exit
      ;;
    shutdown)
      _shutdown ; exit
 esac
 shift 
done
