#!/bin/bash

get-date() {
  echo $(date "+%A_%R_%d-%m-%y")
}

freeze-select() {
  maim -u | feh -F - &
  feh_pid=$!
  while [ -z "$(xdotool search --pid "$feh_pid")" ]; do
      sleep 0.1
  done
}

outline_color="0.38,0.68,0.93"


while [[ "$1" ]]; do
  case "$1" in
    select|s)
      freeze-select
      maim -us -c $outline_color -b 4 "~/Pictures/screenshots/$(get-date).png"
      kill $feh_pid
      ;;
    select-copy|scp)
      freeze-select
      maim -us -c $outline_color -b 4 | xclip -selection clipboard -t image/png
      kill $feh_pid
      ;;
    full|f)
      maim -u "~/Pictures/screenshots/$(get-date).png"
      ;;
    full-copy|fcp)
      maim -u | xclip -selection clipboard -t image/png
      ;;
  esac
  exit
done
